---
- name: install python-passlib
  apt: >
    name=python-passlib
    state=present

- name: add a user to the .htpasswd file
  htpasswd: >
    path=/etc/nginx/.htpasswd
    name={{ item.user }}
    password={{ item.password }}
    owner=root
    group=www-data
    mode=0640
  with_items: '{{ nginx_htpasswd }}'
