---
- include: install_2.4.yml
  when: mongodb.version < "2.6"
  tags:
    - install_mongos
    - install

- include: install_2.6.yml
  when: mongodb.version >= "2.6" and mongodb.version < "3.0"
  tags:
    - install_mongos
    - install

- include: install_3.0.yml
  when: mongodb.version >= "3.0" and mongodb.version < "3.2"
  tags:
    - install_mongos
    - install

- include: install_3.2.yml
  when: mongodb.version >= "3.2"
  tags:
    - install_mongos
    - install

- include: auth.yml
  when: mongodb.version >= "3.0" and mongodb.auth is defined
  tags:
    - auth_mongos
    - auth

- include: configure_2.4.yml
  when: mongodb.version < "2.6"
  tags:
    - configure_mongos
    - configure

- include: configure_2.6.yml
  when: mongodb.version >= "2.6" and mongodb.version < "3.0"
  tags:
    - configure_mongos
    - configure

- include: configure_3.0.yml
  when: mongodb.version >= "3.0" and mongodb.version < "3.2"
  tags:
    - configure_mongos
    - configure

- include: configure_3.2.yml
  when: mongodb.version >= "3.2"
  tags:
    - configure_mongos
    - configure

- include: logrotate.yml
  tags:
    - logrotate_mongos
    - logrotate
