---
- hosts: all
#  remote_user: root
  become: yes
#  vars_files:
#     - "group_vars/{{inventory_file}}/elk-serv.yml"

  roles:
    - { role: aws_asg_hostname, tags: aws_asg_hostname }
    - { role: nagios-nrpe, tags: nagios-nrpe }
