---
- name: install dependencies for mongodb plugin
  apt: >
    name={{ item }}
  with_items:
    - build-essential
    - python-dev
    - python-pip

- name: install dependencies for mongodb plugin
  pip: >
    name=pymongo
#    version=2.8

- name: upgrade pymongo package
  pip: >
    name=pymongo
    extra_args='--upgrade'

- name: copy nagios plugins
  copy: >
    src=plugins/{{ item }}
    dest=/usr/lib/nagios/plugins
    mode=0755
  with_items:
    - check_mongodb.py
