---
- name: install python-passlib
  apt: >
    name=python-passlib
    state=present

- name: add a user to the password file
  htpasswd: >
    path=/etc/nagios3/htpasswd.users
    name={{ item.user }}
    password={{ item.password }}
    owner=root
    group=www-data
    mode=0640
  with_items: nagios3_htpasswd
